### ISSUE TITLE
Cade a página inicial

### ISSUE THREAD

**Issue by bmarchete** [fakebmarchete/mestre-github#1]
Vocês poderiam fazer a página inicial, não acham?

**Comment by fakebmarchete** [comment]
Ok, farei isso o mais rápido possível!

**Comment by fakebmarchete** [comment]
@bmarchete Fiz alterações no commit e132d6b1275c153909895eae6aea7a56e2f470f9

**Comment by bmarchete** [comment]
👍

**Comment by fakebmarchete** [comment]
Ok. Finalizando issue!

Em qua, 13 de set de 2017 às 21:00, João Rubens Marchete Filho <
notifications@github.com> escreveu:
