### ISSUE TITLE
Criar página de contato

### ISSUE THREAD

**Issue by bmarchete** [fakebmarchete/mestre-github#2]
Seria bem legal visualizar uma página de contato!

**Comment by fakebmarchete** [comment]
Começando a desenvolver!

**Comment by bmarchete** [comment]
👍

**Comment by fakebmarchete** [comment]
Encerrando issue

**Comment by fakebmarchete** [comment]
Porque nao foi


Em qua, 13 de set de 2017 às 21:09, João Rubens Marchete Filho <
notifications@github.com> escreveu:
